### ISSUE TITLE
Torrent returns an errror - not possible to download

### ISSUE THREAD

**Issue by cropscout** [lyrk/true-marble-edit#1]
It seems it is not anymore possible to download the files via Torrent... the torrent client tells error on connection to server.

Could you please update the link?

Or are the data available on some public URL?

Do you know you can make a Release on GitHub - and attach several files - each up to 2 GBytes?
https://help.github.com/articles/distributing-large-binaries/

**Comment by ubahnverleih** [comment]
Could you try the Torrent again? (connection Errors maybe come from some unavailable trackers, but there some working trackers in the torrent, and also DHT should work now)

**Comment by cropscout** [comment]
Thanks for fast response. So far no success. Will keep it trying with transmission-cli client.
Are the files each bigger than 2 GBytes?

**Comment by cropscout** [comment]
Download runs now. Thanks!

**Comment by ubahnverleih** [comment]
added HTTP download in e37de06094605f0b74ab8c310bef523757bef882
